language: minimal

addons:
  snaps:
  - snapcraft

jobs:
  include:
  - stage: build snap with snapcraft on default Ubuntu 14.04
    install: cat /etc/os-release
    script: snapcraft --version && snapcraft
