language: minimal

dist: xenial

addons:
  apt:
    packages:
    - snapcraft

jobs:
  include:
  - stage: build snap with snapcraft on Ubuntu 16.04 (xenial)
    install: cat /etc/os-release
    script: snapcraft --version && snapcraft
