language: minimal

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script: echo "doing nothing"

    # deploy stage doesn't define own script: and there is
    # no default script: at the root level, and therefore
    # nothing is run at this stage
    - stage: deploy
